name: Django application on docker - lint and run tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the stack
      run: docker-compose -f docker-compose.override.github-actions.yml up -d
    - name: Lint with ruff
      run: docker-compose -f docker-compose.override.github-actions.yml exec -T goldenhands ruff check .
    - name: Test with pytest
      run: docker-compose -f docker-compose.override.github-actions.yml exec -T goldenhands pytest
